name: Masha
favicon: null
layout_spectrum: 0.8419079806189984
typography_spectrum: 0.2335522382054478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#6a96c3'
    - '#1b1b1b'
    - '#395c72'
    - '#c2aea5'
  brandStrength: 0
  lightness: 0.5197355540003628
  saturation: 0.27369888848625124
  rhythmicContrast: 0.40836096880957484
purpose: []
