name: Masha
favicon: null
layout_spectrum: 0.86269
typography_spectrum: 0.97651
title: Lovely Bones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#6a96c3'
    - '#1b1b1b'
    - '#395c72'
    - '#c2aea5'
  brandStrength: 0
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
